/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/capture.glb --transform 
Files: public/capture.glb [14.94MB] > C:\Users\luisg\OneDrive - Universidade de Lisboa\MSc\Personal\portfolio\capture-transformed.glb [770.71KB] (95%)
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/capture-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="easyglider-body-one-piece" scale={0.01} />
        <mesh name="capture" geometry={nodes.capture.geometry} material={materials.Blue} position={[-0.001, 1.034, -0.007]} rotation={[0.031, -1.168, -0.257]} />
        <mesh name="capture003" geometry={nodes.capture003.geometry} material={nodes.capture003.material} position={[-0.001, 1.034, -0.007]} rotation={[0.031, -1.168, -0.257]} />
        <mesh name="capture004" geometry={nodes.capture004.geometry} material={materials.Black} position={[-0.001, 1.034, -0.007]} rotation={[0.031, -1.168, -0.257]} />
        <group name="easyglider-body-one-piece002" position={[0.072, 0.49, 0]} rotation={[0.145, -1.008, 0.031]} scale={0.001}>
          <mesh name="easyglider-body-one-piece002_1" geometry={nodes['easyglider-body-one-piece002_1'].geometry} material={nodes['easyglider-body-one-piece002_1'].material} />
          <mesh name="easyglider-body-one-piece002_2" geometry={nodes['easyglider-body-one-piece002_2'].geometry} material={materials['Material.001']} />
          <mesh name="easyglider-body-one-piece002_3" geometry={nodes['easyglider-body-one-piece002_3'].geometry} material={materials.Black} />
        </group>
        <mesh name="simplify_M690B_10pct_001" geometry={nodes.simplify_M690B_10pct_001.geometry} material={materials.DefaultMaterial} position={[-0.001, 1.034, -0.007]} rotation={[-1.302, 0.1, -2.556]} scale={0.0006} />
      </group>
    </group>
  )
}

useGLTF.preload('/capture-transformed.glb')
