/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/TLM05e.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/TLM05e.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.164, 0.934, 0.297]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={0.976}>
        <mesh geometry={nodes.carenagem_0_0.geometry} material={materials['Carbon_Fiber_Rough_5mm_#1_263858686']} />
        <mesh geometry={nodes.carenagem_0_0_1.geometry} material={materials['Carbon_Fiber_Rough_5mm_#9_1059']} />
        <mesh geometry={nodes.carenagem_0_0_2.geometry} material={materials['Carbon_Fiber_Rough_5mm_#2_263858687']} />
        <mesh geometry={nodes.carenagem_0_0_3.geometry} material={materials.PaletteMaterial001} />
        <mesh geometry={nodes.carenagem_0_0_4.geometry} material={materials['Carbon_Fiber_Rough_5mm_#17_1301']} />
        <mesh geometry={nodes.carenagem_0_0_5.geometry} material={materials['Carbon_Fiber_Rough_5mm_#1_1722']} />
        <mesh geometry={nodes.carenagem_0_0_6.geometry} material={materials['Carbon_Fiber_Rough_5mm_#12_1767']} />
        <mesh geometry={nodes.carenagem_0_0_7.geometry} material={materials['Carbon_Fiber_Rough_5mm_#18_519763']} />
        <mesh geometry={nodes.carenagem_0_0_8.geometry} material={materials['Titanium Textured #4']} />
        <mesh geometry={nodes.carenagem_0_0_9.geometry} material={materials['Soft Textured Black #3']} />
        <mesh geometry={nodes.carenagem_0_0_10.geometry} material={materials['Titanium Textured #4.001']} />
        <mesh geometry={nodes.carenagem_0_0_11.geometry} material={materials['Titanium Textured #4.002']} />
        <mesh geometry={nodes.carenagem_0_0_12.geometry} material={materials['Aluminum Brushed #17']} />
        <mesh geometry={nodes.carenagem_0_0_13.geometry} material={materials['Aluminum Brushed #17.001']} />
        <mesh geometry={nodes.carenagem_0_0_14.geometry} material={materials['Aluminum Brushed #17.002']} />
        <mesh geometry={nodes.carenagem_0_0_15.geometry} material={materials['Titanium Textured #4.003']} />
        <mesh geometry={nodes.carenagem_0_0_16.geometry} material={materials['Titanium Textured #4.004']} />
        <mesh geometry={nodes.carenagem_0_0_17.geometry} material={materials['Titanium Textured #4.005']} />
        <mesh geometry={nodes.carenagem_0_0_18.geometry} material={materials['Titanium Textured #4.006']} />
        <mesh geometry={nodes.carenagem_0_0_19.geometry} material={materials['Titanium Textured #4.007']} />
        <mesh geometry={nodes.carenagem_0_0_20.geometry} material={materials['Titanium Textured #4.008']} />
        <mesh geometry={nodes.carenagem_0_0_21.geometry} material={materials['Titanium Textured #4.009']} />
        <mesh geometry={nodes.carenagem_0_0_22.geometry} material={materials['Titanium Textured #4.010']} />
        <mesh geometry={nodes.carenagem_0_0_23.geometry} material={materials['Titanium Textured #4.011']} />
        <mesh geometry={nodes.carenagem_0_0_24.geometry} material={materials['Titanium Textured #4.012']} />
        <mesh geometry={nodes.carenagem_0_0_25.geometry} material={materials['Titanium Textured #4.013']} />
        <mesh geometry={nodes.carenagem_0_0_26.geometry} material={materials['Titanium Textured #4.014']} />
        <mesh geometry={nodes.carenagem_0_0_27.geometry} material={materials['Titanium Textured #4.015']} />
        <mesh geometry={nodes.carenagem_0_0_28.geometry} material={materials['Titanium Textured #4.016']} />
        <mesh geometry={nodes.carenagem_0_0_29.geometry} material={materials['Soft Textured Black #3.001']} />
        <mesh geometry={nodes.carenagem_0_0_30.geometry} material={materials['Soft Textured Black #3.002']} />
        <mesh geometry={nodes.carenagem_0_0_31.geometry} material={materials['Aluminum Brushed #17.003']} />
        <mesh geometry={nodes.carenagem_0_0_32.geometry} material={materials.PaletteMaterial002} />
        <mesh geometry={nodes.carenagem_0_0_33.geometry} material={materials['Aluminum Brushed #17.004']} />
        <mesh geometry={nodes.carenagem_0_0_34.geometry} material={materials['Aluminum Brushed #17.005']} />
        <mesh geometry={nodes.carenagem_0_0_35.geometry} material={materials['Aluminum Brushed #17.006']} />
        <mesh geometry={nodes.carenagem_0_0_36.geometry} material={materials['Aluminum Brushed #17.007']} />
        <mesh geometry={nodes.carenagem_0_0_37.geometry} material={materials['Aluminum Brushed #17.008']} />
        <mesh geometry={nodes.carenagem_0_0_38.geometry} material={materials['Aluminum Brushed #17.009']} />
        <mesh geometry={nodes.carenagem_0_0_39.geometry} material={materials['Aluminum Brushed #17.010']} />
        <mesh geometry={nodes.carenagem_0_0_40.geometry} material={materials['Aluminum Brushed #17.011']} />
        <mesh geometry={nodes.carenagem_0_0_41.geometry} material={materials['Aluminum Brushed #17.012']} />
        <mesh geometry={nodes.carenagem_0_0_42.geometry} material={materials['Aluminum Brushed #17.013']} />
        <mesh geometry={nodes.carenagem_0_0_43.geometry} material={materials['Soft Textured Black #3.003']} />
        <mesh geometry={nodes.carenagem_0_0_44.geometry} material={materials['Aluminum Brushed #17.014']} />
        <mesh geometry={nodes.carenagem_0_0_45.geometry} material={materials['Aluminum Brushed #17.015']} />
        <mesh geometry={nodes.carenagem_0_0_46.geometry} material={materials['Aluminum Brushed #17.016']} />
        <mesh geometry={nodes.carenagem_0_0_47.geometry} material={materials['Aluminum Brushed #17.017']} />
        <mesh geometry={nodes.carenagem_0_0_48.geometry} material={materials['Aluminum Brushed #17.018']} />
        <mesh geometry={nodes.carenagem_0_0_49.geometry} material={materials['Aluminum Brushed #17.019']} />
        <mesh geometry={nodes.carenagem_0_0_50.geometry} material={materials['Aluminum Brushed #17.020']} />
        <mesh geometry={nodes.carenagem_0_0_51.geometry} material={materials['Aluminum Brushed #17.021']} />
        <mesh geometry={nodes.carenagem_0_0_52.geometry} material={materials['Aluminum Brushed #17.022']} />
        <mesh geometry={nodes.carenagem_0_0_53.geometry} material={materials['Aluminum Brushed #17.023']} />
        <mesh geometry={nodes.carenagem_0_0_54.geometry} material={materials['Aluminum Brushed #17.024']} />
        <mesh geometry={nodes.carenagem_0_0_55.geometry} material={materials['Aluminum Brushed #17.025']} />
        <mesh geometry={nodes.carenagem_0_0_56.geometry} material={materials['Aluminum Brushed #17.026']} />
        <mesh geometry={nodes.carenagem_0_0_57.geometry} material={materials['Aluminum Brushed #1']} />
        <mesh geometry={nodes.carenagem_0_0_58.geometry} material={materials['Aluminum Brushed #17.027']} />
        <mesh geometry={nodes.carenagem_0_0_59.geometry} material={materials['Aluminum Brushed #17.028']} />
        <mesh geometry={nodes.carenagem_0_0_60.geometry} material={materials.PaletteMaterial003} />
        <mesh geometry={nodes.carenagem_0_0_61.geometry} material={materials['Aluminum Brushed #17.029']} />
        <mesh geometry={nodes.carenagem_0_0_62.geometry} material={materials['Soft Textured Black #3.004']} />
        <mesh geometry={nodes.carenagem_0_0_63.geometry} material={materials['Aluminum Brushed #17.030']} />
        <mesh geometry={nodes.carenagem_0_0_64.geometry} material={materials['Aluminum Brushed #17.031']} />
        <mesh geometry={nodes.carenagem_0_0_65.geometry} material={materials['Aluminum Brushed #17.032']} />
        <mesh geometry={nodes.carenagem_0_0_66.geometry} material={materials['Aluminum Brushed #17.033']} />
        <mesh geometry={nodes.carenagem_0_0_67.geometry} material={materials['Aluminum Brushed #17.034']} />
        <mesh geometry={nodes.carenagem_0_0_68.geometry} material={materials['Aluminum Brushed #17.035']} />
        <mesh geometry={nodes.carenagem_0_0_69.geometry} material={materials['Aluminum Brushed #17.036']} />
        <mesh geometry={nodes.carenagem_0_0_70.geometry} material={materials['Aluminum Brushed #17.037']} />
        <mesh geometry={nodes.carenagem_0_0_71.geometry} material={materials['Aluminum Brushed #17.038']} />
        <mesh geometry={nodes.carenagem_0_0_72.geometry} material={materials['Soft Textured Black #3.005']} />
        <mesh geometry={nodes.carenagem_0_0_73.geometry} material={materials['Soft Textured Black #3.006']} />
        <mesh geometry={nodes.carenagem_0_0_74.geometry} material={materials['Aluminum Brushed #17.039']} />
        <mesh geometry={nodes.carenagem_0_0_75.geometry} material={materials['Aluminum Brushed #17.040']} />
        <mesh geometry={nodes.carenagem_0_0_76.geometry} material={materials['Aluminum Brushed #17.041']} />
        <mesh geometry={nodes.carenagem_0_0_77.geometry} material={materials['Aluminum Brushed #17.042']} />
        <mesh geometry={nodes.carenagem_0_0_78.geometry} material={materials['Aluminum Brushed #17.043']} />
        <mesh geometry={nodes.carenagem_0_0_79.geometry} material={materials['Soft Textured Black #3.007']} />
        <mesh geometry={nodes.carenagem_0_0_80.geometry} material={materials['Aluminum Brushed #17.044']} />
        <mesh geometry={nodes.carenagem_0_0_81.geometry} material={materials['Titanium Textured #4.017']} />
        <mesh geometry={nodes.carenagem_0_0_82.geometry} material={materials['Titanium Textured #4.018']} />
        <mesh geometry={nodes.carenagem_0_0_83.geometry} material={materials['Titanium Textured #4.019']} />
        <mesh geometry={nodes.carenagem_0_0_84.geometry} material={materials['Titanium Textured #4.020']} />
        <mesh geometry={nodes.carenagem_0_0_85.geometry} material={materials['Titanium Textured #4.021']} />
        <mesh geometry={nodes.carenagem_0_0_86.geometry} material={materials['Titanium Textured #4.022']} />
        <mesh geometry={nodes.carenagem_0_0_87.geometry} material={materials['Soft Textured Black #3.008']} />
        <mesh geometry={nodes.carenagem_0_0_88.geometry} material={materials['Soft Textured Black #3.009']} />
        <mesh geometry={nodes.carenagem_0_0_89.geometry} material={materials['Soft Textured Black #3.010']} />
        <mesh geometry={nodes.carenagem_0_0_90.geometry} material={materials['Soft Textured Black #3.011']} />
        <mesh geometry={nodes.carenagem_0_0_91.geometry} material={materials['Aluminum Brushed #17.045']} />
        <mesh geometry={nodes.carenagem_0_0_92.geometry} material={materials['Soft Textured Black #3.012']} />
        <mesh geometry={nodes.carenagem_0_0_93.geometry} material={materials['Aluminum Brushed #17.046']} />
        <mesh geometry={nodes.carenagem_0_0_94.geometry} material={materials['Aluminum Brushed #17.047']} />
        <mesh geometry={nodes.carenagem_0_0_95.geometry} material={materials['Aluminum Brushed #17.048']} />
        <mesh geometry={nodes.carenagem_0_0_96.geometry} material={materials['Aluminum Brushed #17.049']} />
        <mesh geometry={nodes.carenagem_0_0_97.geometry} material={materials['Aluminum Brushed #17.050']} />
        <mesh geometry={nodes.carenagem_0_0_98.geometry} material={materials['Aluminum Brushed #17.051']} />
        <mesh geometry={nodes.carenagem_0_0_99.geometry} material={materials['Aluminum Brushed #17.052']} />
        <mesh geometry={nodes.carenagem_0_0_100.geometry} material={materials['Aluminum Brushed #17.053']} />
        <mesh geometry={nodes.carenagem_0_0_101.geometry} material={materials['Anodized Aluminum Brushed 90° Black #7']} />
        <mesh geometry={nodes.carenagem_0_0_102.geometry} material={materials['Soft Textured Black #3.013']} />
        <mesh geometry={nodes.carenagem_0_0_103.geometry} material={materials['Soft Textured Black #3.014']} />
        <mesh geometry={nodes.carenagem_0_0_104.geometry} material={materials['Soft Textured Black #3.015']} />
        <mesh geometry={nodes.carenagem_0_0_105.geometry} material={materials['Aluminum Brushed #17.054']} />
        <mesh geometry={nodes.carenagem_0_0_106.geometry} material={materials['Aluminum Brushed #17.055']} />
        <mesh geometry={nodes.carenagem_0_0_107.geometry} material={materials['Aluminum Brushed #17.056']} />
        <mesh geometry={nodes.carenagem_0_0_108.geometry} material={materials['Soft Textured Black #3.016']} />
        <mesh geometry={nodes.carenagem_0_0_109.geometry} material={materials['Soft Textured Black #3.017']} />
        <mesh geometry={nodes.carenagem_0_0_110.geometry} material={materials['Soft Textured Black #3.018']} />
        <mesh geometry={nodes.carenagem_0_0_111.geometry} material={materials['Soft Textured Black #3.019']} />
        <mesh geometry={nodes.carenagem_0_0_112.geometry} material={materials['Soft Textured Black #3.020']} />
        <mesh geometry={nodes.carenagem_0_0_113.geometry} material={materials['Soft Textured Black #3.021']} />
        <mesh geometry={nodes.carenagem_0_0_114.geometry} material={materials['Soft Textured Black #3.022']} />
        <mesh geometry={nodes.carenagem_0_0_115.geometry} material={materials['Soft Textured Black #3.023']} />
        <mesh geometry={nodes.carenagem_0_0_116.geometry} material={materials['Soft Textured Black #3.024']} />
        <mesh geometry={nodes.carenagem_0_0_117.geometry} material={materials['Soft Textured Black #3.025']} />
        <mesh geometry={nodes.carenagem_0_0_118.geometry} material={materials['Soft Textured Black #3.026']} />
        <mesh geometry={nodes.carenagem_0_0_119.geometry} material={materials['Aluminum Brushed #17.057']} />
        <mesh geometry={nodes.carenagem_0_0_120.geometry} material={materials['Aluminum Brushed #17.058']} />
        <mesh geometry={nodes.carenagem_0_0_121.geometry} material={materials['Aluminum Brushed #17.059']} />
        <mesh geometry={nodes.carenagem_0_0_122.geometry} material={materials['Aluminum Brushed #17.060']} />
        <mesh geometry={nodes.carenagem_0_0_123.geometry} material={materials['Aluminum Brushed #17.061']} />
        <mesh geometry={nodes.carenagem_0_0_124.geometry} material={materials['Aluminum Brushed #17.062']} />
        <mesh geometry={nodes.carenagem_0_0_125.geometry} material={materials['Soft Textured Black #3.027']} />
        <mesh geometry={nodes.carenagem_0_0_126.geometry} material={materials['Soft Textured Black #3.028']} />
        <mesh geometry={nodes.carenagem_0_0_127.geometry} material={materials['Aluminum Brushed #17.063']} />
        <mesh geometry={nodes.carenagem_0_0_128.geometry} material={materials['Soft Textured Black #3.029']} />
        <mesh geometry={nodes.carenagem_0_0_129.geometry} material={materials['Soft Textured Black #3.030']} />
        <mesh geometry={nodes.carenagem_0_0_130.geometry} material={materials['Soft Textured Black #3.031']} />
        <mesh geometry={nodes.carenagem_0_0_131.geometry} material={materials['Soft Textured Black #3.032']} />
        <mesh geometry={nodes.carenagem_0_0_132.geometry} material={materials['Soft Textured Black #3.033']} />
        <mesh geometry={nodes.carenagem_0_0_133.geometry} material={materials['Soft Textured Black #3.034']} />
        <mesh geometry={nodes.carenagem_0_0_134.geometry} material={materials['Soft Textured Black #3.035']} />
        <mesh geometry={nodes.carenagem_0_0_135.geometry} material={materials['Soft Textured Black #3.037']} />
        <mesh geometry={nodes.carenagem_0_0_136.geometry} material={materials['Soft Textured Black #3.039']} />
        <mesh geometry={nodes.carenagem_0_0_137.geometry} material={materials['Soft Textured Black #3.041']} />
        <mesh geometry={nodes.carenagem_0_0_138.geometry} material={materials['Soft Textured Black #3.042']} />
        <mesh geometry={nodes.carenagem_0_0_139.geometry} material={materials['Soft Textured Black #3.044']} />
        <mesh geometry={nodes.carenagem_0_0_140.geometry} material={materials['Soft Textured Black #3.047']} />
        <mesh geometry={nodes.carenagem_0_0_141.geometry} material={materials['Soft Textured Black #3.048']} />
        <mesh geometry={nodes.carenagem_0_0_142.geometry} material={materials['Soft Textured Black #3.049']} />
        <mesh geometry={nodes.carenagem_0_0_143.geometry} material={materials['Titanium Textured #4.023']} />
        <mesh geometry={nodes.carenagem_0_0_144.geometry} material={materials['Aluminum Brushed #17.064']} />
        <mesh geometry={nodes.carenagem_0_0_145.geometry} material={materials['Aluminum Brushed #17.065']} />
        <mesh geometry={nodes.carenagem_0_0_146.geometry} material={materials['Aluminum Brushed #17.066']} />
        <mesh geometry={nodes.carenagem_0_0_147.geometry} material={materials.PaletteMaterial004} />
        <mesh geometry={nodes.carenagem_0_0_148.geometry} material={materials['Soft Textured Black #3.051']} />
        <mesh geometry={nodes.carenagem_0_0_149.geometry} material={materials['Soft Textured Black #3.052']} />
        <mesh geometry={nodes.carenagem_0_0_150.geometry} material={materials['Aluminum Brushed #17.067']} />
        <mesh geometry={nodes.carenagem_0_0_151.geometry} material={materials['Aluminum Brushed #17.068']} />
        <mesh geometry={nodes.carenagem_0_0_152.geometry} material={materials['Aluminum Brushed #17.069']} />
        <mesh geometry={nodes.carenagem_0_0_153.geometry} material={materials['Carbon Fiber Rough 5mm #2.001']} />
        <mesh geometry={nodes.carenagem_0_0_154.geometry} material={materials['Soft Textured Black #3.061']} />
        <mesh geometry={nodes.carenagem_0_0_155.geometry} material={materials['Soft Textured Black #3.062']} />
        <mesh geometry={nodes.carenagem_0_0_156.geometry} material={materials['Soft Textured Black #3.063']} />
        <mesh geometry={nodes.carenagem_0_0_157.geometry} material={materials['Soft Textured Black #3.064']} />
        <mesh geometry={nodes.carenagem_0_0_158.geometry} material={materials['Soft Textured Black #3.065']} />
        <mesh geometry={nodes.carenagem_0_0_159.geometry} material={materials['Soft Textured Black #3.066']} />
        <mesh geometry={nodes.carenagem_0_0_160.geometry} material={materials['Soft Textured Black #3.067']} />
        <mesh geometry={nodes.carenagem_0_0_161.geometry} material={materials['Soft Textured Black #3.068']} />
        <mesh geometry={nodes.carenagem_0_0_162.geometry} material={materials['Soft Textured Black #3.069']} />
        <mesh geometry={nodes.carenagem_0_0_163.geometry} material={materials['Soft Textured Black #3.070']} />
        <mesh geometry={nodes.carenagem_0_0_164.geometry} material={materials['Soft Textured Black #3.071']} />
        <mesh geometry={nodes.carenagem_0_0_165.geometry} material={materials['Soft Textured Black #3.072']} />
        <mesh geometry={nodes.carenagem_0_0_166.geometry} material={materials['Soft Textured Black #3.073']} />
        <mesh geometry={nodes.carenagem_0_0_167.geometry} material={materials['Soft Textured Black #3.074']} />
        <mesh geometry={nodes.carenagem_0_0_168.geometry} material={materials['Soft Textured Black #3.075']} />
        <mesh geometry={nodes.carenagem_0_0_169.geometry} material={materials['Soft Textured Black #3.076']} />
        <mesh geometry={nodes.carenagem_0_0_170.geometry} material={materials['Carbon Fiber Rough 5mm #2']} />
        <mesh geometry={nodes.carenagem_0_0_171.geometry} material={materials.PaletteMaterial005} />
        <mesh geometry={nodes.carenagem_0_0_172.geometry} material={materials['Soft Textured Black #3.036']} />
        <mesh geometry={nodes.carenagem_0_0_173.geometry} material={materials['Soft Textured Black #3.043']} />
      </group>
    </group>
  )
}

useGLTF.preload('/TLM05e.glb')
