/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/YCB.glb --transform 
Files: public/YCB.glb [76.96KB] > C:\Users\luisg\OneDrive - Universidade de Lisboa\MSc\Personal\portfolio\YCB-transformed.glb [13.36KB] (83%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/YCB-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube001.geometry} material={materials['Material.002']} position={[0.999, 2.753, -0.452]} rotation={[1.569, 0, 0]} scale={[0.47, 0.47, 1.088]} />
      <mesh geometry={nodes.Cube013.geometry} material={materials['Material.003']} position={[0.776, 2.757, -0.013]} rotation={[-3.045, 1.569, -1.729]} scale={[0.68, 0.657, 0.724]} />
      <mesh geometry={nodes.Cube014.geometry} material={materials['Material.004']} position={[0.032, 3.515, -0.013]} rotation={[-1.572, 0, 3.079]} scale={[0.68, 0.657, 0.724]} />
      <mesh geometry={nodes.Cube015.geometry} material={materials['Material.005']} position={[0.032, 2.751, -0.612]} rotation={[3.14, 0, 3.079]} scale={[0.68, 0.657, 0.491]} />
      <mesh geometry={nodes.Cube_Material_0.geometry} material={materials['Material.001']} position={[0, 2.754, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.909, 0.398, 1.098]} />
    </group>
  )
}

useGLTF.preload('/YCB-transformed.glb')
